### ISSUE TITLE
Comparison with transducers?

### ISSUE THREAD

**Issue by FranklinChen** [tonyday567/sfold#1]
It might be interesting and useful to compare your sfold concept explicitly to "transducers" as introduced for Clojure (and then ported/debated elsewhere).

**Comment by tonyday567** [comment]
You prompted my first look ay Clojure transducers, and in getting up to speed, I happen to be reading your article.  Before I got there I was readying myself to translate clojure to haskell but you've done the job :)

Here's my reading list.  Anything else I should look at?

https://gist.github.com/tel/8f6de199626adc0f313b
https://github.com/FranklinChen/clojure-transducers-in-haskell
http://blog.podsnap.com/ducers.html
http://thecomputersarewinning.com/post/Transducers-Are-Fundamental/
http://www.reddit.com/r/haskell/comments/2cv6l4/clojures_transducers_are_perverse_lenses/

~~~    
    "The notion of a transducer is related to the way Oleg builds mappings between iteratees as  enumeratees.

    Most lens combinators restricted to the case that you have them taking in a Fold and spitting out a   Fold are 'transducers'."

~~~

https://hackage.haskell.org/package/machines

**Comment by FranklinChen** [comment]
I have not actually kept up with the discussions of transducers or continued exploring them, I'm afraid, although I want to get back to that topic, but you might want to look at the interpretation of transducers by Cognitect Labs for several languages and 

https://cognitect-labs.github.io/
